# Algebra Linear Computacional
## Notebook 3 - Decomposições complexas
### **Aluno**: Lucas Silva de Sousa 
________________

No presente notebook serão serão apresentados os resultados obtidos com as implementações dos métodos decomposição QR e formas de obtenção de auto-valores e auto-vetores. As implementações dos métodos foram feitos utilizando a linguagem Python 3. Os códigos fontes foram organizados em módulos e classes orientadas a objeto. A organização dos códigos seguem a seguinte estrutura: 

- Módulo *lib* contém as bibliotecas que foram elaboradas com com as operações.
- Módulo *notebooks* são armazenados os códigos das simulações realizadas com os métodos.

Os tópicos que serão tratados neste notebook são: 

1. Método QR
    - Ortogonalizarão de Gran-Shimidt
    - Decomposição QR por matrizes de rotação *
    - Decomposição QR por matrizes de reflexão
2. Autovalores e autovetores
    - Método da potência: Regular, inverso e com deslocamento *
    - Métodos de transformações de similaridade: Householder + QR 

Na próxima célula é realizada a importação das bibliotecas necessárias para o trabalho.

In [5]:
import sys
sys.path.append("../")

import numpy as np
from lib.matrix import Matrix
from lib.linear_system import gauss_elimination, gauss_elimination_reduction
from lib.decompositions import QR_method_gram_sh, QR_method_hh, eign_qr_hh

### 1. Método QR

O método QR é uma forma de decomposição de uma matriz em um produto de uma matriz ortogonal $\mathbf{Q}$ e uma outra matriz triangular superior $\mathbf{R}$. 

#### 1.1. Método QR via ortogonalização de gram-shmidt
A primeira forma de se obter a decomposição QR, é através do método de ortogonalização de Gram-shmidt. Esse método realiza uma conversão de um espaço vetorial em um espaço vetorial ortonormal ortogonal. Sua aplicação no método QR é bem direta, pois o resultado direto do método de gram-shmidt é a própria matriz $\mathbf{Q}$. Daí, para se encontrar a matriz $\mathbf{R}$, basta se resolver os sistemas de equações lineares que ocorrem entre as colunas da matriz $\mathbf{A}$ em relação à sua decomposição $\mathbf{A} = \mathbf{Q}\mathbf{R}$.

A seguir é apresentado o resultado da implementação do método QR através da ortogonalização de Gram-shmidt. Considere a matriz 

$\mathbf{A} = 
\begin{bmatrix}
3 & 2 & 4 \\
1 & 1 & 2 \\
4 & 3 & -2
\end{bmatrix}$

In [6]:
# criação da matriz A e aplicação do método QR implementado

A = np.array([[3.0, 2.0, 4.0], [1.0, 1.0, 2.0], [4.0, 3.0, -2.0]])
ma = Matrix(A)

Q, R = QR_method_gram_sh(ma)

In [7]:
# Matriz Q
print(Q)

[[ 0.58834841 -0.56613852  0.57735027]
 [ 0.19611614  0.79259392  0.57735027]
 [ 0.78446454  0.22645541 -0.57735027]]


In [8]:
# Matriz R

print(R)

[[ 5.09901951  3.72620656  1.17670296]
 [ 0.          0.33968314 -1.13229283]
 [ 0.          0.          4.61880431]]


In [9]:
# aplicação do produto entre as matrizes QR a fim de se obter a matriz A novamente.

print(np.matmul(Q, R))

[[ 3.          1.99999998  4.0000138 ]
 [ 1.          1.00000002  1.99998993]
 [ 4.          3.         -2.        ]]


Observe que na célula acima, é apresentado o produto entre as matrizes Q e R a fim de se reconstruir a matriz A. É possível observar que o valor resultante é bem aproximado, exceto por algumas casas decimais.

#### 1.2. Método QR via householder

O método de householder pode ser aplicado diretamente na decomposição QR. O método de householder recebe como entrada uma matriz $\mathbf{A}$ com dimensões $(m \times n)$. O método irá resultar em uma matriz com dimensões $(m \times m)$. O processo é realizado de forma iterativa em que a matriz resultante é obtida a partir de multiplicações simultâneas de novas matrizes obtidas a cada iteração. A cada iteração, a matriz $\mathbf{Z}$ é recalculada com base na equação a seguir: 

$\mathbf{Z}_i = \mathbf{I} - \mathcal{vv}^\intercal$,

em que a matriz v é calculada seguindo os seguintes passos: 

1. $\mathcal{e} = ||\mathcal{a}_1|| * [1, 0, 0 ... 0]_{1 \times m}$, em que $\mathcal{a_1}$ é a primeira coluna da matriz A.
2. $\mathcal{u} = \mathcal{x} - \mathcal{e}$
3. $\mathcal{v} = \frac{\mathcal{u}}{||\mathcal{u}||}$

Vale observar que na primeira iteração do método, $\mathcal{a}_1$ será a primeira coluna da matriz $\mathbf{A}$, mas a partir da segunda iteração, o vetor $\mathcal{v}$ será calculado com base na matriz $\mathbf{Z}$ sem a primeira linha e a primeira coluna. Consequentemente, o vetor $\mathcal{v}$ que será obtido terá uma dimensão a menos em relação a iteração anterior. A cada iteração, a matriz $\mathbf{Z}$ será atualizada de modo que $\mathbf{Z}_{i + 1} = \mathbf{Z}_{i + 1}\mathbf{Z}_{i}$. Para isso, a matriz $\mathbf{Z}_{i + 1}$ deverá ter uma linha acima e à esquerda adicionada com zeros, exceto pelo elemento da posição $(0, 0)$ que será igual a 1.

Ao final do algoritmo, a matriz $\mathbf{R} = \mathbf{Z}\mathbf{A}$ e a matriz $\mathbf{Q} = \mathbf{Z}$.

Nas próximas células são apresentados os resultados da implementação.

In [10]:
# matriz utilizada na simulação

T = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]])
mt = Matrix(T)

In [11]:
# aplicação do método 

Q, R = QR_method_hh(mt)

In [12]:
# apresentação da matriz Q

print(Q)

[[ 0.85714286 -0.39428571  0.33142857]
 [ 0.42857143  0.90285714 -0.03428571]
 [-0.28571429  0.17142857  0.94285714]]


In [13]:
# apresentação da matriz R

print(R)

[[ 14.  21. -14.]
 [  0. 175. -70.]
 [  0.   0. -35.]]


In [14]:
# produto entre as matrizes QR para se obter a matriz T novamente

print(np.matmul(Q, R))

[[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]]


### 2. Autovalores e Autovetores

Dada uma matriz $\mathbf{A}$, podemos encontrar seus autovalores e autovetores utilizando o método QR. Nessa implementação foi utilizada QR + Householder. Considerando a equação a seguir: 

$\mathbf{A}\mathcal{a} = \lambda \mathbf{a}$

nesse caso, $\lambda$ é um autovalor associado e o vetor $\mathcal{a}$ é dito um autovetor. Utilizando o método QR, a diagonal da matriz $\mathbf{R}$ é composta pelos autovalores da matriz $\mathbf{A}$. Desse modo, podemos resolver o sistema linear homogeneo gerado com cada autovalor a fim de se obter cada um dos autovetores associados.

A resolução do sistema linear homogêneo ocorreu através do método de eliminação da gauss, mas com um chute inicial para uma das variáveis. Isso fez com que a solução obtida não fosse a trivial.

In [15]:
D, eign = eign_qr_hh(mt)

In [16]:
#matriz de autovetores

print(D)

[[-0.99923195 -0.29884446  0.24969758]
 [ 0.03918557  0.94434828  0.30226549]
 [-0.         -0.13747118  0.91993842]]


In [18]:
# vetor de autovalores
print(eign)

[ 14. 175. -35.]
