# Algebra Linear Computacional
## Notebook 2 - Resolução de sistema lineares e decomposições
### **Aluno**: Lucas Silva de Sousa 
________________

No presente notebook serão serão apresentados os resultados obtidos com as implementações dos métodos resolução de sistemas lineares e decomposições de matrizes. As implementações dos métodos foram feitos utilizando a linguagem Python 3. Os códigos fontes foram organizados em módulos e classes orientadas a objeto. A organização dos códigos seguem a seguinte estrutura: 

- Módulo *lib* contém as bibliotecas que foram elaboradas com com as operações.
- Módulo *notebooks* são armazenados os códigos das simulações realizadas com os métodos.

Os tópicos que serão tratados neste notebook são: 

1. Método de eliminação de gauss
    - Forma escalonada
    - Forma escalonada reduzida
2. fatoração de Cholesky
3. Resolução de sistemas através da equação normal
3. Fatoração LU

Na próxima célula é realizada a importação das bibliotecas necessárias para o trabalho e a classe **Matrix** juntamente com as funções do módulo *linear_system*.

In [358]:
import sys
sys.path.append("../")

import numpy as np
from lib.matrix import Matrix
from lib.linear_system import gauss_elimination, gauss_elimination_reduction

### 1. Método de eliminação de Gauss

O método de eliminação da Gauss é utilizado para resolução de sistemas lineares. O método faz uso da matriz aumentada do sistema linear na forma escalonada para encontrar os valores dos coeficientes do sistema através do processo de retro-substituição. Para analisar os resultados do método implementado, iremos utilizar a seguinte matriz:

$D = \begin{bmatrix}
2 & 1 & 0 & 3 & 4\\
1 & 1 & -1 & 1 & 1\\
1 & -1 & -1 & 2 & -3\\
-3 & 2 & 3 & -1 & 4\\
\end{bmatrix}$

A carga da matriz será realizada na célula a seguir:

In [359]:
d = np.array([[2, 1, 0, 3, 4], [1, 1, -1, 1, 1], [1, -1, -1, 2, -3], [-3, 2, 3, -1, 4]]) # 4x5
md = Matrix(d)

print(md.data)

[[ 2.  1.  0.  3.  4.]
 [ 1.  1. -1.  1.  1.]
 [ 1. -1. -1.  2. -3.]
 [-3.  2.  3. -1.  4.]]


A Função *gauss_elimination* recebe a matriz aumentada $D$ e retorna um vetor de coeficientes das quatro variáveis do sistema linear correspondente. A saber,

In [360]:
x = gauss_elimination(md)
print(x)

[[ 2.16667579  1.66667175  2.16667056 -0.66667222]]


Uma possível variação do método de eliminação de Gauss faz uso da matriz escalonada reduzida. Nesse caso, como a matriz dos coeficientes resultantes possui somente valores 1 nos pivôs, a substituição do vetor resultante é direta. Esse método é chamado de *Gauss-Jordan* e foi implementado através da função *gauss_elimination_reduction*. A seguir o método é aplicado à matriz $D$. Note que são obtidos resultados similares ao método da eliminação de Gauss.

In [361]:
y = gauss_elimination_reduction(md)
print(y)

[[ 2.16669  1.66669  2.16667 -0.66667]]


### 2. Fatoração de Cholesky

A Fatoração de Cholesky pode ser aplicada à matrizes simétricas e positivas definidas. Esse método é capaz de decompor uma Matriz $\mathbf{A}$ de dimensões $(n \times n)$ de modo que $\mathbf{A} = \mathbf{G}\mathbf{G}^\intercal$. Para demonstrar, considere a matriz simétrica e positiva definida a seguir:

$
\mathbf{F} = \begin{bmatrix}
4 & 2 & -4\\
2 & 10 & 4\\ 
-4 & 4 & 9
\end{bmatrix}$

Nas próximas células é apresentado o código de aplicação do método de Cholesky para decomposição da matriz $\mathbf{F}$.

In [362]:
# instanciação da matriz F

f = np.array([[4, 2, -4], [2, 10, 4], [-4, 4, 9]])
mf = Matrix(f)

print(mf.data)

[[ 4.  2. -4.]
 [ 2. 10.  4.]
 [-4.  4.  9.]]


In [363]:
# execução do método cholesky da classe Matrix

G, G_t = mf.cholesky()

In [364]:
# Matriz G
print(G.data)

[[ 2.  0.  0.]
 [ 1.  3.  0.]
 [-2.  2.  1.]]


In [365]:
# Matriz G_t
print(G_t.data)

[[ 2.  1. -2.]
 [ 0.  3.  2.]
 [ 0.  0.  1.]]


Com o produto entre as matrizes $G$ e $G^\intercal$ é possível reconstruir a matriz $\mathbf{F}$ novamente.

In [366]:
F_rec = G.matrix_product(G_t)
print(F_rec.data)

[[ 4.  2. -4.]
 [ 2. 10.  4.]
 [-4.  4.  9.]]


### 3. Resolução de sistemas lineares através da equação normal

Considerando o sistema linear na forma $\mathbf{A}\mathcal{x} = \mathcal{b}$ em que \mathbf{A} possui dimensões $(m \times n)$, \mathcal{x} possui dimensões $(n \times 1)$ e o vetor $\mathcal{b}$ possui dimensões $\mathcal{m} \times 1$. Nos casos em que $m > n$ Podemos reescrever a equação na forma: 

$\mathbf{A}^\intercal\mathbf{A}\mathcal{x} = \mathbf{A}^\intercal\mathcal{b}$

Desse modo, o sistema pode ser resolvido através do método de eliminação de Gauss ou Gauss-Jordan, visto que a Matriz $\mathbf{A}^\intercal\mathbf{A}$ é quadrada.

Para demonstrar a resolução desse problema, iremos dividir a matriz aumentada $\mathbf{D}$ em duas matrizes contendo os coeficientes e um vetor com o resultado. Assim,

$\mathbf{A} = \begin{bmatrix}
2 & 1 & 0 & 3\\
1 & 1 & -1 & 1\\
1 & -1 & -1 & 2\\
-3 & 2 & 3 & -1
\end{bmatrix}$ e $
\mathcal{b} = \begin{bmatrix}
4\\
1\\
-3\\
4
\end{bmatrix}$

Nas próximas células será realizada essa divisão das matrizes em Python.

In [367]:
b = np.array([d[:, -1]]).T

In [368]:
A = d[:, 0:d.shape[1] - 1]
print(A)

[[ 2  1  0  3]
 [ 1  1 -1  1]
 [ 1 -1 -1  2]
 [-3  2  3 -1]]


In [369]:
# Obtenção de uma nova matriz aumentada após o produto pela transposta e aplicação da eliminação de Gauss no novo sistema.
A = np.matmul(A.T, A)
b = np.matmul(A.T, b)

A_aum = np.concatenate((A, b), axis=1)
M_A_aum = Matrix(A_aum)

result = gauss_elimination(M_A_aum)
print(result.T)

[[ 4.00002098]
 [ 0.99999896]
 [-2.99998314]
 [ 3.99998889]]


Note que o resultado obtido é igual ao vetor $\mathcal{b}$.

### 3. Fatoração LU

O método de fatoração LU consiste de uma forma de representar uma matriz $\mathbf{A}$ com dimensões $n \times n$ como o produto de duas outras matrizes $\mathbf{L}$ e $\mathbf{U}$. Vale observar que a matriz $\mathbf{L}$ é diagonal inferior e a matriz $\mathbf{U}$ é triangular superior. O processo de decomposição da matriz LU pode ser feito refatorando um pouco o processo de escalonamento da matriz por pivotação parcial, visto que a matriz $U$ é a triangular superior resultante do processo de escalonamento. A matriz triangular inferior é composta pelos multiplicadores calculados a partir dos pivôs no processo de pivotação parcial. O procedimento pode ser utilizado para simplificar a resolução de sistemas lineares.

Como demonstração do método, considere o sistema linear a seguir: 

$
\mathbf{Z} = \begin{bmatrix}
2 & 1 & 1 & 0\\ 
4 & 3 & 3 & 1\\ 
8 & 7 & 9 & 5\\ 
6 & 7 & 9 & 8\\ 
\end{bmatrix}
$ e $\mathcal{p} = \begin{bmatrix}
2\\ 
2\\ 
4\\ 
5 
\end{bmatrix}$

A seguir é apresentada a forma de resolução do sistema linear baseado na fatoração LU. Vale observar que o método de fatoração faz parte da classe **Matrix** no módulo *lib*.

In [375]:
# Aplicação do método de fatoração LU na matriz A

Z = np.array([[2, 1, 1, 0], [4, 3, 3, 1], [8, 7, 9, 5], [6, 7, 9, 8]])
p = np.array([[2, 2, 4, 5]]).T

mz = Matrix(Z)
mp = Matrix(p)

L, U, sw_lines = mz.fatoracao_lu()
mp.data = mp.data[sw_lines]

Como o método de fatoração LU implementado fez uso da pivotação parcial, linhas podem ter sido trocadas, daí a matriz *sw_lines* irá servir para reordenar o vetor $\mathcal{p}$.

In [376]:
# Matriz L

print(L.data)

[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.25       -0.42857143  1.          0.        ]
 [ 0.75       -0.28571429  0.33333333  1.        ]]


In [377]:
# Matriz U

print(U.data)

[[ 8.          7.          9.          5.        ]
 [ 0.          1.75        2.25        4.25      ]
 [ 0.          0.         -0.85714286 -0.28571429]
 [ 0.          0.          0.          0.66666667]]


Para resolver o sistema linear a partir das matrizes $\mathbf{L}$ e $\mathbf{U}$, realizamos os dois passos: 

- Resolver o sistema $\mathbf{L}\mathcal{y} = \mathcal{b}$
- Depois resolver o sistema $\mathbf{U}\mathcal{x} = \mathcal{y}$

Assim,

In [378]:
#Resolvendo o primeiro sistema linear a fim de se obter o valor de y
L_aum = np.concatenate((L.data, mp.data), axis=1)
y = gauss_elimination(Matrix(L_aum)).T
print(y)

[[ 4.     ]
 [ 3.     ]
 [ 2.28571]
 [-0.90477]]


In [379]:
#Resolvendo o segundo sistema linear a fim de se obter o valor de x
U_aum = np.concatenate((U.data, y), axis=1)
x = gauss_elimination(Matrix(U_aum)).T

print(x)

[[-3.0357325 ]
 [ 7.85716071]
 [-2.21427667]
 [-1.357155  ]]
