# Algebra Linear Computacional
## Notebook 1 - Operações com matrizes
### **Aluno**: Lucas Silva de Sousa 
________________

No presente notebook serão serão apresentados os resultados obtidos com as implementações dos métodos de operações básicas com matrizes. As implementações dos métodos foram feitos utilizando a linguagem Python 3. Os códigos fontes foram organizados em módulos e classes orientadas a objeto. A organização dos códigos seguem a seguinte estrutura: 

- Módulo *lib* contém as bibliotecas que foram elaboradas com com as operações.
- Módulo *notebooks* são armazenados os códigos das simulações realizadas com os métodos.

Os tópicos que serão tratados neste notebook são: 

1. Produto escalar
2. Produto matriz - vetor
3. Produto matriz - matriz
4. Forma escalonada da matriz
    1. Forma escalonada reduzida e não-reduzida com pivotação parcial

Na próxima célula é realizada a importação das bibliotecas necessárias para o trabalho e a classe **Matrix** que foi definida com os métodos.

In [25]:
import sys
sys.path.append("../")

import numpy as np
from lib.matrix import Matrix

### Matrizes e vetores utilizadas nas simulações

A fim de validar as implementações dos métodos, foram utilizadas as seguintes matrizes:

$
A = \begin{bmatrix}
4 & 3\\ 
6 & 3
\end{bmatrix}
$, $
B = \begin{bmatrix}
3 & 3 & 1\\
4 & 5 & 9 
\end{bmatrix}
$, $
C = \begin{bmatrix}
2 & 1 & 1 & 3\\
3 & 7 & 9 & 1\\
1 & 4 & -11 & 10
\end{bmatrix}
$, $
D = \begin{bmatrix}
2 & 1 & 0 & 3 & 4\\
1 & 1 & -1 & 1 & 1\\
1 & -1 & -1 & 2 & -3\\
-3 & 2 & 3 & -1 & 4\\
\end{bmatrix}
$, $
E = \begin{bmatrix}
3 & 4 & 1 \\
2 & 2 & 1 \\
3 & 4 & 5
\end{bmatrix}
$

Além das matrizes, também serão utilizados os escalares $\alpha = 0,5$, $\lambda = 2$, e $\sigma = 0,3$ e os vetores a seguir:

$\mathcal{x} = \begin{bmatrix}
3 \\
2 \\
3
\end{bmatrix}
$ e $
\mathcal{y} = \begin{bmatrix}
4, -1, 2, 7
\end{bmatrix}$.

Na célula a seguir, são instanciadas os arrays e os objetos da classe Matrix contendo os dados de teste.


In [26]:
# matrizes

a = np.array([[4, 3], [6, 3]]) # 2x2
b = np.array([[3, 3, 1], [4, 5, 9]]) # 2x3
c = np.array([[2, 1, 1, 3], [3, 7, 9, 1], [1, 4, -11, 10]]) # 3x4
d = np.array([[2, 1, 0, 3, 4], [1, 1, -1, 1, 1], [1, -1, -1, 2, -3], [-3, 2, 3, -1, 4]]) # 4x5
e = np.array([[3, 4, 1], [2, 2, 1], [3, 4, 5]]) # 3x3

ma = Matrix(a)
mb = Matrix(b)
mc = Matrix(c)
md = Matrix(d)
me = Matrix(e)

# vetores

x = np.array([[3], [2], [3]]) # 3x1
y = np.array([[4, -1, 2, 7]]) # 1x4

mx = Matrix(x)
my = Matrix(y)

# escalares

alpha = 0.5
lambd = 2
sigma = 0.3

### 1. Produto escalar

O produto escalar de matrizes consiste em multiplicar cada componente individualmente da matriz por um valor constante. Para demonstrar esse tipo de operação, a seguir são apresentados os resultados dos produtos $\alpha A$ e $\lambda B$. Tal produto pode ser realizado através do método *scalar_product* da classe **Matrix**.

In [27]:
R1 = ma.scalar_product(alpha).data
print(R1)

[[2.  1.5]
 [3.  1.5]]


In [28]:
R2 = mb.scalar_product(lambd).data
print(R2)

[[ 6.  6.  2.]
 [ 8. 10. 18.]]


### 2. Produto matriz-vetor

Essa operação se trata de multiplicar uma matriz com dimensões $(m \times n)$ por um vetor com dimensões $(n \times 1)$. O resultado dessa operação deve ser um vetor com dimensões $(m \times 1)$. A fim de se avaliar o modelo implementado, serão realizadas as seguintes operações:

- Produto $A\mathcal{x}$ - O resultado deve ser um erro pelo fato das dimensões serem incompatíveis
- Produto $B\mathcal{x}$ - O resultado deve ser um vetor com dimensões $(2 \times 1)$
- Produto $E\mathcal{x}$ - O resultado deve ser um vetor com dimensões $(3 \times 1)$

In [29]:
R3 = ma.matrix_product(mx)

Erro - As dimensões das matrizes são incompatíveis para realização do produto.


In [30]:
R4 = mb.matrix_product(mx).data
print(R4)

[[18.]
 [49.]]


In [31]:
R5 = me.matrix_product(mx).data
print(R5)

[[20.]
 [13.]
 [32.]]


### 3. Produto matriz-matriz

O produto entre duas matrizes pode ser realizado entre uma matriz de dimensão $(m \times n)$ e outra matriz $(k \times j)$, caso $n = k$. A matriz resultante do produto terá dimensão $(m \times j)$. Para validação da implementação, serão apresentados os resultados das seguintes operações:

- AB - Deve resultar em uma matriz de dimensão $(2 \times 3)$
- BE - Deve resultar em uma matriz de dimensão $(2 \times 3)$
- DC - Deve resultar em erro devido as dimensões incompatíveis

In [32]:
AB = ma.matrix_product(mb)
print(AB.data)

[[24. 27. 31.]
 [30. 33. 33.]]


In [33]:
BE = mb.matrix_product(me)
print(BE.data)

[[18. 22. 11.]
 [49. 62. 54.]]


In [34]:
DC = md.matrix_product(mc)

Erro - As dimensões das matrizes são incompatíveis para realização do produto.


### 4. Forma escalonada da matriz

A forma escalonada de uma matriz é uma ferramenta essencial para resolução de sistemas lineares, que são métodos que serão apresentados nos próximos notebooks. Uma abordagem para se obter a forma escalonada de uma matriz consiste de realizar operações lineares entre as linhas de modo que a matriz termine o processo na forma triangular superior. No presente trabalho, foi utilizada uma metodologia de **pivotação parcial** em que além das operações lineares entre as linhas da matriz, também são feitas trocas de linhas específicas. Uma matriz é dita estar na forma escalonada caso algumas regras sejam seguidas. A saber:

- O primeiro elemento não-zero de uma coluna da matriz (pivô) não poderá ter nenhum valor não-nulo abaixo dele.
- Todo elemento pivô deverá estar à direita do pivô da coluna imediatamente anterior e uma linha abaixo.

Além disso, existe uma outra abordagem de escalonamento de matrizes que resultam na forma escalonada reduzida. Uma matriz pertence à essa forma se: 

- Ela pertence a forma escalonada.
- Todo elemento pivô possui valor 1.
- Todos os valores acima e abaixo do pivô, na mesma coluna, devem ser nulos.

A seguir são apresentados os resultados obtidos do escalonamento reduzido e não-reduzido das matrizes $D$, $C$ e $E$.

In [35]:
# Forma escalonada da matriz D com pivotação parcial

D_esc = md.partial_pivot_echelon()
print(D_esc.data)

[[-3.       2.       3.      -1.       4.     ]
 [ 0.       2.33333  2.       2.33333  6.66667]
 [ 0.       0.      -1.42858 -1.      -2.42859]
 [ 0.       0.       0.       1.8     -1.20001]]


In [37]:
# Forma escalonada reduzida da matriz D com pivotação parcial

D_esc_red = md.partial_pivot_echelon_reduced()
print(D_esc_red.data)

[[ 1.       0.       0.       0.       2.16669]
 [ 0.       1.       0.       0.       1.66669]
 [ 0.       0.       1.       0.       2.16667]
 [ 0.       0.       0.       1.      -0.66667]]


In [38]:
# Forma escalonada da matriz C com pivotação parcial

C_esc = mc.partial_pivot_echelon()
print(C_esc.data)

[[  3.        7.        9.        1.     ]
 [  0.       -3.66667  -5.        2.33333]
 [  0.        0.      -16.27273  10.72728]]


In [39]:
# Forma escalonada reduzida da matriz C com pivotação parcial

C_esc_red = mc.partial_pivot_echelon_reduced()
print(C_esc_red.data)

[[ 1.       0.       0.       1.69832]
 [ 0.       1.       0.       0.26258]
 [ 0.       0.       1.      -0.65922]]


In [41]:
# Forma escalonada da matriz E com pivotação parcial

E_esc = me.partial_pivot_echelon()
print(E_esc.data)

[[ 3.       4.       1.     ]
 [ 0.      -0.66667  0.33333]
 [ 0.       0.       4.     ]]


In [43]:
# Forma escalonada reduzida da matriz E com pivotação parcial

E_esc_red = me.partial_pivot_echelon_reduced()
print(E_esc_red.data)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
